<a href="https://colab.research.google.com/github/PrudhviNarayanKorupolu/5731assignment4_korupolu/blob/main/INFO5731_Assignment_Four_(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **INFO5731 Assignment Four**

In this assignment, you are required to conduct topic modeling, sentiment analysis based on **the dataset you created from assignment three**.

# **Question 1: Topic Modeling**

(30 points). This question is designed to help you develop a feel for the way topic modeling works, the connection to the human meanings of documents. Based on the dataset from assignment three, write a python program to **identify the top 10 topics in the dataset**. Before answering this question, please review the materials in lesson 8, especially the code for LDA and LSA. The following information should be reported:

(1) Features (top n-gram phrases) used for topic modeling.

(2) Top 10 clusters for topic modeling.

(3) Summarize and describe the topic for each cluster.

In [12]:
# Write your code here
import pandas as pd
my_data=pd.read_csv('dataset.csv')
print(my_data.shape)

(3798, 3)

In [15]:
import nltk   #cleaning
my_data['Text'] = my_data['Text'].str.replace('[^\w\s]','')  #removal of punctuation
my_data['Text'] = my_data['Text'].apply(lambda x: " ".join(x.lower() for x in x.split()))#lower case
from nltk.corpus import stopwords #removal of stopwords
nltk.download('stopwords')
stop = stopwords.words('english')
my_data['Text'] = my_data['Text'].apply(lambda x: " ".join(x for x in x.split() if x not in stop))

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [16]:
words = []   #building document-term matrix
from nltk.tokenize import RegexpTokenizer
from gensim import corpora,models
tokenizer = RegexpTokenizer(r'\w+')
for x in pd.Series(imdb_data['Text']):
  a = tokenizer.tokenize(x)
  words.append(a)
dictionary = corpora.Dictionary(words)
corpus = [dictionary.doc2bow(word) for word in words]

In [17]:
import gensim  #LDA model
model = gensim.models.ldamodel.LdaModel(corpus, num_topics = 10, id2word = dictionary,passes = 20)

In [18]:
print(model.print_topics(num_topics = 10, num_words = 5))

[(0, '0.019*"online" + 0.018*"shopping" + 0.014*"coronavirus" + 0.013*"store" + 0.012*"food"'), (1, '0.014*"covid19" + 0.012*"coronavirus" + 0.011*"food" + 0.006*"due" + 0.006*"stock"'), (2, '0.045*"covid_19" + 0.030*"store" + 0.028*"grocery" + 0.021*"supermarket" + 0.016*"coronavirus"'), (3, '0.023*"coronavirus" + 0.017*"online" + 0.016*"covid19" + 0.013*"shopping" + 0.009*"prices"'), (4, '0.022*"food" + 0.020*"people" + 0.018*"coronavirus" + 0.015*"grocery" + 0.014*"store"'), (5, '0.014*"coronavirus" + 0.013*"food" + 0.012*"covid19" + 0.008*"hand" + 0.007*"stock"'), (6, '0.017*"coronavirus" + 0.016*"store" + 0.012*"grocery" + 0.011*"covid19" + 0.009*"covid_19"'), (7, '0.016*"coronavirus" + 0.012*"prices" + 0.012*"covid19" + 0.008*"covid_19" + 0.006*"consumer"'), (8, '0.038*"food" + 0.021*"stock" + 0.019*"covid19" + 0.019*"coronavirus" + 0.017*"people"'), (9, '0.021*"food" + 0.019*"coronavirus" + 0.017*"stock" + 0.010*"covid19" + 0.009*"home"')]

# **Question 2: Sentiment Analysis**

(30 points). Sentiment analysis also known as opinion mining is a sub field within Natural Language Processing (NLP) that builds machine learning algorithms to classify a text according to the sentimental polarities of opinions it contains, e.g., positive, negative, neutral. The purpose of this question is to develop a machine learning classifier for sentiment analysis. Based on the dataset from assignment three, write a python program to implement a sentiment classifier and evaluate its performance. Notice: **80% data for training and 20% data for testing**.  

(1) Features used for sentiment classification and explain why you select these features.

(2) Select two of the supervised learning algorithm from scikit-learn library: https://scikit-learn.org/stable/supervised_learning.html#supervised-learning, to build a sentiment classifier respectively. 

(3) Compare the performance over accuracy, precision, recall, and F1 score for the two algorithms you selected. Here is the reference of how to calculate these metrics: https://towardsdatascience.com/accuracy-precision-recall-or-f1-331fb37c5cb9.

In [20]:
# Write your code here
import pandas as pd
my_data=pd.read_csv('dataset.csv')
print(my_data.shape)

(3798, 3)

In [22]:
my_data['sentiment'].value_counts()

-1    1633
 1    1546
 0     619
Name: sentiment, dtype: int64

In [25]:
import nltk
my_data['Text'] = my_data['Text'].str.replace('[^\w\s]','')  #removal of punctuation
my_data['Text'] = my_data['Text'].apply(lambda x: " ".join(x.lower() for x in x.split()))#lower case
from nltk.corpus import stopwords #removal of stopwords
nltk.download('stopwords')
stop = stopwords.words('english')
my_data['Text'] = my_data['Text'].apply(lambda x: " ".join(x for x in x.split() if x not in stop))

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [27]:
my_data.head()

                                                Text  sentiment    result
0  trending new yorkers encounter empty supermark...         -1  Negative
1  couldnt find hand sanitizer fred meyer turned ...          1   Neutral
2                find protect loved ones coronavirus          1  Positive
3  panic buying hits newyork city anxious shopper...         -1   Neutral
4  toiletpaper dunnypaper coronavirus coronavirus...          0   Neutral

In [28]:
my_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3798 entries, 0 to 3797
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Text       3798 non-null   object
 1   sentiment  3798 non-null   int64
 2   result     1630 non-null   object
dtypes: int64(1), object(2)
memory usage: 89.1+ KB

In [29]:
from sklearn.feature_extraction.text import TfidfVectorizer

tf_idf= TfidfVectorizer(ngram_range=(1,2), max_features=1000)
tf_idf.fit(my_data['Text'])
x_values =  tf_idf.transform(my_data['Text'])
y_values = my_data['sentiment']


# Split the training data to training and validating data
from sklearn.model_selection import train_test_split
x_train, x_valid, y_train, y_valid = train_test_split(x_values, y_values, test_size = 0.2)

In [41]:
from sklearn import metrics

def evaluation(y_pred, y_test):
    Accuracy = metrics.accuracy_score(y_pred, y_test)
    Recall = metrics.recall_score(y_pred = y_pred, y_true = y_test, pos_label='positive', average='micro') # micro calculates total true positives, false negatives and false positives
    Precision = metrics.precision_score(y_pred = y_pred, y_true = y_test, pos_label='positive', average='micro') # micro calculates total true positives, false negatives and false positives
    F1 = 2 * (Precision * Recall) / (Precision + Recall) # Formula for F1 Score
    print("Accuracy: ", Accuracy.round(2))
    print("Recall:", Recall.round(2))
    print("Precision:", Precision.round(2))
    print("F-1 score:", F1.round(2))

In [46]:
from sklearn import naive_bayes
from sklearn.model_selection import cross_val_score, KFold

naive_bayes_implement = naive_bayes.MultinomialNB()

naive_bayes_implement.fit(x_train,y_train)

y_pred_valid = naive_bayes_implement.predict(x_valid)
evaluation(y_pred_valid, y_valid)

Accuracy:  0.61
Recall: 0.61
Precision: 0.61
F-1 score: 0.61

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1365: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  UserWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1365: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  UserWarning,

In [48]:
from sklearn import svm

svm_implement = svm.SVC()

svm_implement.fit(x_train,y_train)

y_pred_valid = svm_implement.predict(x_valid)
evaluation(y_pred_valid, y_valid)

Accuracy:  0.64
Recall: 0.64
Precision: 0.64
F-1 score: 0.64

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1365: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  UserWarning,
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1365: UserWarning: Note that pos_label (set to 'positive') is ignored when average != 'binary' (got 'micro'). You may use labels=[pos_label] to specify a single positive class.
  UserWarning,

# **Question 3: House price prediction**

(40 points). You are required to build a **regression** model to predict the house price with 79 explanatory variables describing (almost) every aspect of residential homes. The purpose of this question is to practice regression analysis, an supervised learning model. The training data, testing data, and data description files can be download here: https://github.com/unt-iialab/info5731_spring2021/blob/main/assignment/assignment4-question3-data.zip. Here is an axample for implementation: https://towardsdatascience.com/linear-regression-in-python-predict-the-bay-areas-home-price-5c91c8378878.

In [69]:
# Write your code here
at = pd.read_csv("test.csv")
ae = pd.read_csv("train.csv")

In [52]:
at

        Id  MSSubClass MSZoning  ...  SaleType  SaleCondition SalePrice
0        1          60       RL  ...        WD         Normal    208500
1        2          20       RL  ...        WD         Normal    181500
2        3          60       RL  ...        WD         Normal    223500
3        4          70       RL  ...        WD        Abnorml    140000
4        5          60       RL  ...        WD         Normal    250000
...    ...         ...      ...  ...       ...            ...       ...
1455  1456          60       RL  ...        WD         Normal    175000
1456  1457          20       RL  ...        WD         Normal    210000
1457  1458          70       RL  ...        WD         Normal    266500
1458  1459          20       RL  ...        WD         Normal    142125
1459  1460          20       RL  ...        WD         Normal    147500

[1460 rows x 81 columns]

In [70]:
ae

        Id  MSSubClass MSZoning  ...  SaleType  SaleCondition SalePrice
0        1          60       RL  ...        WD         Normal    208500
1        2          20       RL  ...        WD         Normal    181500
2        3          60       RL  ...        WD         Normal    223500
3        4          70       RL  ...        WD        Abnorml    140000
4        5          60       RL  ...        WD         Normal    250000
...    ...         ...      ...  ...       ...            ...       ...
1455  1456          60       RL  ...        WD         Normal    175000
1456  1457          20       RL  ...        WD         Normal    210000
1457  1458          70       RL  ...        WD         Normal    266500
1458  1459          20       RL  ...        WD         Normal    142125
1459  1460          20       RL  ...        WD         Normal    147500

[1460 rows x 81 columns]

In [84]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression


ae = ae.select_dtypes(include=['number']).interpolate().dropna()
at = at.select_dtypes(include=['number']).interpolate().dropna()

x = df_test.drop(['SalePrice','Id'], axis=1)
y = np.log(df_test.SalePrice)


trainx, testx, trainy, testy = train_test_split(x,y,random_state = 21, test_size=0.2)


regression = LinearRegression()
regression.fit(trainx,trainy)

predy = regression.predict(testx)

In [82]:
print('Linear Regression R squared": %.4f' % regression.score(testx, testy))

Linear Regression R squared": 0.8493

In [85]:
import numpy as np
from sklearn.metrics import mean_squared_error
lin = mean_squared_error(np.exp(predy), testy)
lin_r = np.sqrt(lin)
print(lin_r)

195747.2801595339

In [87]:
results = {"Predicted Prices":np.exp(predy),"Actual Prices":np.exp(testy)}
val = pd.DataFrame(results)
val["Percentage Difference"] = round(abs((val["Predicted Prices"] - val["Actual Prices"]) / val["Actual Prices"]) * 100,2)
val

      Predicted Prices  Actual Prices  Percentage Difference
880      156677.762126       157000.0                   0.21
605      229973.921577       205000.0                  12.18
1166     245358.948864       245350.0                   0.00
216      218109.586021       210000.0                   3.86
970       86909.329260       135000.0                  35.62
...                ...            ...                    ...
218      231419.797074       311500.0                  25.71
1228     311321.804719       367294.0                  15.24
1007      93234.996099        88000.0                   5.95
575      109041.447359       118500.0                   7.98
599      172431.414374       151000.0                  14.19

[292 rows x 3 columns]